# Generated by Django 5.1.1 on 2024-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_appointment_bill_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('available_slots', models.IntegerField(default=20)),
            ],
        ),
         migrations.RunSQL(
            """
            CREATE TRIGGER decrement_slots
            AFTER INSERT ON yourapp_appointment
            BEGIN
                UPDATE yourapp_slotavailability
                SET available_slots = available_slots - 1
                WHERE section = NEW.slot AND available_slots > 0;
            END;
            """
        ),
    ]
