# Generated by Django 5.1.2 on 2024-10-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_slotavailability_date_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotavailability',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='slotavailability',
            unique_together={('section', 'date')},
        ),
    ]
