# Generated by Django 5.1.2 on 2024-10-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_slotavailability_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotavailability',
            unique_together={('date', 'section')},
        ),
    ]
